BattleFrontier_Lounge8_MapScripts:: @ 82676C9
	.byte 0

BattleFrontier_Lounge8_EventScript_2676CA:: @ 82676CA
	msgbox BattleFrontier_Lounge8_Text_2676E5, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_2676D3:: @ 82676D3
	msgbox BattleFrontier_Lounge8_Text_26779C, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_2676DC:: @ 82676DC
	msgbox BattleFrontier_Lounge8_Text_26782C, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_2676E5: @ 82676E5
	.i18n 1939

BattleFrontier_Lounge8_Text_26779C: @ 826779C
	.i18n 1940

BattleFrontier_Lounge8_Text_26782C: @ 826782C
	.i18n 1941

