BattleFrontier_Lounge4_MapScripts:: @ 826358C
	.byte 0

BattleFrontier_Lounge4_EventScript_26358D:: @ 826358D
	msgbox BattleFrontier_Lounge4_Text_2635A8, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_263596:: @ 8263596
	msgbox BattleFrontier_Lounge4_Text_2635EC, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_26359F:: @ 826359F
	msgbox BattleFrontier_Lounge4_Text_263625, MSGBOX_NPC
	end

BattleFrontier_Lounge4_Text_2635A8: @ 82635A8
	.i18n 1871

BattleFrontier_Lounge4_Text_2635EC: @ 82635EC
	.i18n 1872

BattleFrontier_Lounge4_Text_263625: @ 8263625
	.i18n 1873

