SSTidalLowerDeck_MapScripts:: @ 823C818
	.byte 0

SSTidalLowerDeck_EventScript_23C819:: @ 823C819
	trainerbattle_single TRAINER_PHILLIP, SSTidalLowerDeck_Text_23C847, SSTidalLowerDeck_Text_23C8A0
	msgbox SSTidalLowerDeck_Text_23C8B4, MSGBOX_AUTOCLOSE
	end

SSTidalLowerDeck_EventScript_23C830:: @ 823C830
	trainerbattle_single TRAINER_LEONARD, SSTidalLowerDeck_Text_23C917, SSTidalLowerDeck_Text_23C97D
	msgbox SSTidalLowerDeck_Text_23C98E, MSGBOX_AUTOCLOSE
	end

SSTidalLowerDeck_Text_23C847: @ 823C847
	.i18n 4288

SSTidalLowerDeck_Text_23C8A0: @ 823C8A0
	.i18n 4289

SSTidalLowerDeck_Text_23C8B4: @ 823C8B4
	.i18n 4290

SSTidalLowerDeck_Text_23C917: @ 823C917
	.i18n 4291

SSTidalLowerDeck_Text_23C97D: @ 823C97D
	.i18n 4292

SSTidalLowerDeck_Text_23C98E: @ 823C98E
	.i18n 4293

