SeafloorCavern_Room1_MapScripts:: @ 82347EB
	.byte 0

SeafloorCavern_Room1_EventScript_2347EC:: @ 82347EC
	trainerbattle_single TRAINER_GRUNT_5, SeafloorCavern_Room1_Text_23481A, SeafloorCavern_Room1_Text_23484A
	msgbox SeafloorCavern_Room1_Text_23485D, MSGBOX_AUTOCLOSE
	end

SeafloorCavern_Room1_EventScript_234803:: @ 8234803
	trainerbattle_single TRAINER_GRUNT_6, SeafloorCavern_Room1_Text_234898, SeafloorCavern_Room1_Text_2348CD
	msgbox SeafloorCavern_Room1_Text_2348E3, MSGBOX_AUTOCLOSE
	end

SeafloorCavern_Room1_Text_23481A: @ 823481A
	.i18n 4322

SeafloorCavern_Room1_Text_23484A: @ 823484A
	.i18n 4323

SeafloorCavern_Room1_Text_23485D: @ 823485D
	.i18n 4324

SeafloorCavern_Room1_Text_234898: @ 8234898
	.i18n 4325

SeafloorCavern_Room1_Text_2348CD: @ 82348CD
	.i18n 4326

SeafloorCavern_Room1_Text_2348E3: @ 82348E3
	.i18n 4327

