LilycoveCity_ContestHall_MapScripts:: @ 821B484
	.byte 0

LilycoveCity_ContestHall_EventScript_21B485:: @ 821B485
	msgbox LilycoveCity_ContestHall_Text_21B74E, MSGBOX_NPC
	end

LilycoveCity_ContestHall_EventScript_21B48E:: @ 821B48E
	msgbox LilycoveCity_ContestHall_Text_21B7D7, MSGBOX_NPC
	end

LilycoveCity_ContestHall_EventScript_21B497:: @ 821B497
	msgbox LilycoveCity_ContestHall_Text_21B899, MSGBOX_NPC
	end

LilycoveCity_ContestHall_EventScript_21B4A0:: @ 821B4A0
	msgbox LilycoveCity_ContestHall_Text_21B911, MSGBOX_NPC
	end

LilycoveCity_ContestHall_EventScript_21B4A9:: @ 821B4A9
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21B977, MSGBOX_DEFAULT
	closemessage
	applymovement 4, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B4C0:: @ 821B4C0
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21B9DC, MSGBOX_DEFAULT
	closemessage
	applymovement 5, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B4D7:: @ 821B4D7
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BA44, MSGBOX_DEFAULT
	closemessage
	applymovement 6, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B4EE:: @ 821B4EE
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BAD5, MSGBOX_DEFAULT
	closemessage
	applymovement 7, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B505:: @ 821B505
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BB84, MSGBOX_DEFAULT
	closemessage
	applymovement 8, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B51C:: @ 821B51C
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BBDD, MSGBOX_DEFAULT
	closemessage
	applymovement 9, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B533:: @ 821B533
	msgbox LilycoveCity_ContestHall_Text_21BC65, MSGBOX_SIGN
	end

LilycoveCity_ContestHall_EventScript_21B53C:: @ 821B53C
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BC89, MSGBOX_DEFAULT
	closemessage
	applymovement 12, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B553:: @ 821B553
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BD30, MSGBOX_DEFAULT
	closemessage
	applymovement 22, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B56A:: @ 821B56A
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BD70, MSGBOX_DEFAULT
	closemessage
	applymovement 11, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B581:: @ 821B581
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BDDD, MSGBOX_DEFAULT
	closemessage
	applymovement 13, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B598:: @ 821B598
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BE16, MSGBOX_DEFAULT
	closemessage
	applymovement 14, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B5AF:: @ 821B5AF
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BE77, MSGBOX_DEFAULT
	closemessage
	applymovement 15, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B5C6:: @ 821B5C6
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BEDE, MSGBOX_DEFAULT
	closemessage
	applymovement 16, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B5DD:: @ 821B5DD
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BF6E, MSGBOX_DEFAULT
	closemessage
	applymovement 17, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B5F4:: @ 821B5F4
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21BFE3, MSGBOX_DEFAULT
	closemessage
	applymovement 18, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B60B:: @ 821B60B
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C07F, MSGBOX_DEFAULT
	closemessage
	applymovement 19, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B622:: @ 821B622
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C0D8, MSGBOX_DEFAULT
	closemessage
	applymovement 21, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B639:: @ 821B639
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C137, MSGBOX_DEFAULT
	closemessage
	applymovement 20, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B650:: @ 821B650
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C1A4, MSGBOX_DEFAULT
	closemessage
	applymovement 23, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B667:: @ 821B667
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C215, MSGBOX_DEFAULT
	closemessage
	applymovement 24, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B67E:: @ 821B67E
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C27F, MSGBOX_DEFAULT
	closemessage
	applymovement 25, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B695:: @ 821B695
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C2BB, MSGBOX_DEFAULT
	closemessage
	applymovement 26, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B6AC:: @ 821B6AC
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C307, MSGBOX_DEFAULT
	closemessage
	applymovement 27, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B6C3:: @ 821B6C3
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C365, MSGBOX_DEFAULT
	closemessage
	applymovement 28, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B6DA:: @ 821B6DA
	lockall
	applymovement 29, Common_Movement_FacePlayer
	waitmovement 0
	msgbox LilycoveCity_ContestHall_Text_21C3F4, MSGBOX_DEFAULT
	closemessage
	applymovement 29, Common_Movement_FaceOriginalDirection
	waitmovement 0
	delay 25
	msgbox LilycoveCity_ContestHall_Text_21C411, MSGBOX_DEFAULT
	releaseall
	end

LilycoveCity_ContestHall_EventScript_21B705:: @ 821B705
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C4B1, MSGBOX_DEFAULT
	closemessage
	applymovement 31, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B71C:: @ 821B71C
	lock
	faceplayer
	msgbox LilycoveCity_ContestHall_Text_21C445, MSGBOX_DEFAULT
	closemessage
	applymovement 30, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

LilycoveCity_ContestHall_EventScript_21B733:: @ 821B733
	msgbox LilycoveCity_ContestHall_Text_21C512, MSGBOX_SIGN
	end

LilycoveCity_ContestHall_EventScript_21B73C:: @ 821B73C
	msgbox LilycoveCity_ContestHall_Text_21C548, MSGBOX_SIGN
	end

LilycoveCity_ContestHall_EventScript_21B745:: @ 821B745
	msgbox LilycoveCity_ContestHall_Text_21C57B, MSGBOX_SIGN
	end

LilycoveCity_ContestHall_Text_21B74E: @ 821B74E
	.i18n 2490

LilycoveCity_ContestHall_Text_21B7D7: @ 821B7D7
	.i18n 2491

LilycoveCity_ContestHall_Text_21B899: @ 821B899
	.i18n 2492

LilycoveCity_ContestHall_Text_21B911: @ 821B911
	.i18n 2493

LilycoveCity_ContestHall_Text_21B977: @ 821B977
	.i18n 2494

LilycoveCity_ContestHall_Text_21B9DC: @ 821B9DC
	.i18n 2495

LilycoveCity_ContestHall_Text_21BA44: @ 821BA44
	.i18n 2496

LilycoveCity_ContestHall_Text_21BAD5: @ 821BAD5
	.i18n 2497

LilycoveCity_ContestHall_Text_21BB84: @ 821BB84
	.i18n 2498

LilycoveCity_ContestHall_Text_21BBDD: @ 821BBDD
	.i18n 2499

LilycoveCity_ContestHall_Text_21BC65: @ 821BC65
	.i18n 2500

LilycoveCity_ContestHall_Text_21BC89: @ 821BC89
	.i18n 2501

LilycoveCity_ContestHall_Text_21BD30: @ 821BD30
	.i18n 2502

LilycoveCity_ContestHall_Text_21BD70: @ 821BD70
	.i18n 2503

LilycoveCity_ContestHall_Text_21BDDD: @ 821BDDD
	.i18n 2504

LilycoveCity_ContestHall_Text_21BE16: @ 821BE16
	.i18n 2505

LilycoveCity_ContestHall_Text_21BE77: @ 821BE77
	.i18n 2506

LilycoveCity_ContestHall_Text_21BEDE: @ 821BEDE
	.i18n 2507

LilycoveCity_ContestHall_Text_21BF6E: @ 821BF6E
	.i18n 2508

LilycoveCity_ContestHall_Text_21BFE3: @ 821BFE3
	.i18n 2509

LilycoveCity_ContestHall_Text_21C07F: @ 821C07F
	.i18n 2510

LilycoveCity_ContestHall_Text_21C0D8: @ 821C0D8
	.i18n 2511

LilycoveCity_ContestHall_Text_21C137: @ 821C137
	.i18n 2512

LilycoveCity_ContestHall_Text_21C1A4: @ 821C1A4
	.i18n 2513

LilycoveCity_ContestHall_Text_21C215: @ 821C215
	.i18n 2514

LilycoveCity_ContestHall_Text_21C27F: @ 821C27F
	.i18n 2515

LilycoveCity_ContestHall_Text_21C2BB: @ 821C2BB
	.i18n 2516

LilycoveCity_ContestHall_Text_21C307: @ 821C307
	.i18n 2517

LilycoveCity_ContestHall_Text_21C365: @ 821C365
	.i18n 2518

LilycoveCity_ContestHall_Text_21C3F4: @ 821C3F4
	.i18n 2519

LilycoveCity_ContestHall_Text_21C411: @ 821C411
	.i18n 2520

LilycoveCity_ContestHall_Text_21C445: @ 821C445
	.i18n 2521

LilycoveCity_ContestHall_Text_21C4B1: @ 821C4B1
	.i18n 2522

LilycoveCity_ContestHall_Text_21C512: @ 821C512
	.i18n 2523

LilycoveCity_ContestHall_Text_21C548: @ 821C548
	.i18n 2524

LilycoveCity_ContestHall_Text_21C57B: @ 821C57B
	.i18n 2525

