MagmaHideout_2F_1R_MapScripts:: @ 8239B50
	.byte 0

MagmaHideout_2F_1R_EventScript_239B51:: @ 8239B51
	trainerbattle_single TRAINER_GRUNT_51, MagmaHideout_2F_1R_Text_239BAD, MagmaHideout_2F_1R_Text_239C4B
	msgbox MagmaHideout_2F_1R_Text_239C74, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_EventScript_239B68:: @ 8239B68
	trainerbattle_single TRAINER_GRUNT_40, MagmaHideout_2F_1R_Text_239CAB, MagmaHideout_2F_1R_Text_239D09
	msgbox MagmaHideout_2F_1R_Text_239D1D, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_EventScript_239B7F:: @ 8239B7F
	trainerbattle_single TRAINER_GRUNT_41, MagmaHideout_2F_1R_Text_239D62, MagmaHideout_2F_1R_Text_239D75
	msgbox MagmaHideout_2F_1R_Text_239D7D, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_EventScript_239B96:: @ 8239B96
	trainerbattle_single TRAINER_GRUNT_42, MagmaHideout_2F_1R_Text_239DC5, MagmaHideout_2F_1R_Text_239DDA
	msgbox MagmaHideout_2F_1R_Text_239DE2, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_Text_239BAD: @ 8239BAD
	.i18n 2831

MagmaHideout_2F_1R_Text_239C4B: @ 8239C4B
	.i18n 2832

MagmaHideout_2F_1R_Text_239C74: @ 8239C74
	.i18n 2833

MagmaHideout_2F_1R_Text_239CAB: @ 8239CAB
	.i18n 2834

MagmaHideout_2F_1R_Text_239D09: @ 8239D09
	.i18n 2835

MagmaHideout_2F_1R_Text_239D1D: @ 8239D1D
	.i18n 2836

MagmaHideout_2F_1R_Text_239D62: @ 8239D62
	.i18n 2837

MagmaHideout_2F_1R_Text_239D75: @ 8239D75
	.i18n 2838

MagmaHideout_2F_1R_Text_239D7D: @ 8239D7D
	.i18n 2839

MagmaHideout_2F_1R_Text_239DC5: @ 8239DC5
	.i18n 2840

MagmaHideout_2F_1R_Text_239DDA: @ 8239DDA
	.i18n 2841

MagmaHideout_2F_1R_Text_239DE2: @ 8239DE2
	.i18n 2842

