gBerryDescriptionPart1_Cheri:: @ 8589AE4
	.i18n 5794

gBerryDescriptionPart2_Cheri:: @ 8589B09
	.i18n 5795

gBerryDescriptionPart1_Chesto:: @ 8589B2D
	.i18n 5796

gBerryDescriptionPart2_Chesto:: @ 8589B52
	.i18n 5797

gBerryDescriptionPart1_Pecha:: @ 8589B7A
	.i18n 5798

gBerryDescriptionPart2_Pecha:: @ 8589B94
	.i18n 5799

gBerryDescriptionPart1_Rawst:: @ 8589BB9
	.i18n 5800

gBerryDescriptionPart2_Rawst:: @ 8589BDC
	.i18n 5801

gBerryDescriptionPart1_Aspear:: @ 8589C01
	.i18n 5802

gBerryDescriptionPart2_Aspear:: @ 8589C25
	.i18n 5803

gBerryDescriptionPart1_Leppa:: @ 8589C3E
	.i18n 5804

gBerryDescriptionPart2_Leppa:: @ 8589C62
	.i18n 5805

gBerryDescriptionPart1_Oran:: @ 8589C86
	.i18n 5806

gBerryDescriptionPart2_Oran:: @ 8589CAE
	.i18n 5807

gBerryDescriptionPart1_Persim:: @ 8589CCA
	.i18n 5808

gBerryDescriptionPart2_Persim:: @ 8589CEC
	.i18n 5809

gBerryDescriptionPart1_Lum:: @ 8589D11
	.i18n 5810

gBerryDescriptionPart2_Lum:: @ 8589D35
	.i18n 5811

gBerryDescriptionPart1_Sitrus:: @ 8589D54
	.i18n 5812

gBerryDescriptionPart2_Sitrus:: @ 8589D77
	.i18n 5813

gBerryDescriptionPart1_Figy:: @ 8589D98
	.i18n 5814

gBerryDescriptionPart2_Figy:: @ 8589DBA
	.i18n 5815

gBerryDescriptionPart1_Wiki:: @ 8589DD7
	.i18n 5816

gBerryDescriptionPart2_Wiki:: @ 8589DFD
	.i18n 5817

gBerryDescriptionPart1_Mago:: @ 8589E16
	.i18n 5818

gBerryDescriptionPart2_Mago:: @ 8589E39
	.i18n 5819

gBerryDescriptionPart1_Aguav:: @ 8589E5F
	.i18n 5820

gBerryDescriptionPart2_Aguav:: @ 8589E87
	.i18n 5821

gBerryDescriptionPart1_Iapapa:: @ 8589EA6
	.i18n 5822

gBerryDescriptionPart2_Iapapa:: @ 8589EC6
	.i18n 5823

gBerryDescriptionPart1_Razz:: @ 8589EE7
	.i18n 5824

gBerryDescriptionPart2_Razz:: @ 8589F0C
	.i18n 5825

gBerryDescriptionPart1_Bluk:: @ 8589F31
	.i18n 5826

gBerryDescriptionPart2_Bluk:: @ 8589F57
	.i18n 5827

gBerryDescriptionPart1_Nanab:: @ 8589F79
	.i18n 5828

gBerryDescriptionPart2_Nanab:: @ 8589F94
	.i18n 5829

gBerryDescriptionPart1_Wepear:: @ 8589FBA
	.i18n 5830

gBerryDescriptionPart2_Wepear:: @ 8589FE2
	.i18n 5831

gBerryDescriptionPart1_Pinap:: @ 858A007
	.i18n 5832

gBerryDescriptionPart2_Pinap:: @ 858A023
	.i18n 5833

gBerryDescriptionPart1_Pomeg:: @ 858A04A
	.i18n 5834

gBerryDescriptionPart2_Pomeg:: @ 858A066
	.i18n 5835

gBerryDescriptionPart1_Kelpsy:: @ 858A087
	.i18n 5836

gBerryDescriptionPart2_Kelpsy:: @ 858A0AA
	.i18n 5837

gBerryDescriptionPart1_Qualot:: @ 858A0C5
	.i18n 5838

gBerryDescriptionPart2_Qualot:: @ 858A0E7
	.i18n 5839

gBerryDescriptionPart1_Hondew:: @ 858A109
	.i18n 5840

gBerryDescriptionPart2_Hondew:: @ 858A12B
	.i18n 5841

gBerryDescriptionPart1_Grepa:: @ 858A14E
	.i18n 5842

gBerryDescriptionPart2_Grepa:: @ 858A16F
	.i18n 5843

gBerryDescriptionPart1_Tamato:: @ 858A196
	.i18n 5844

gBerryDescriptionPart2_Tamato:: @ 858A1B8
	.i18n 5845

gBerryDescriptionPart1_Cornn:: @ 858A1CF
	.i18n 5846

gBerryDescriptionPart2_Cornn:: @ 858A1F4
	.i18n 5847

gBerryDescriptionPart1_Magost:: @ 858A215
	.i18n 5848

gBerryDescriptionPart2_Magost:: @ 858A239
	.i18n 5849

gBerryDescriptionPart1_Rabuta:: @ 858A253
	.i18n 5850

gBerryDescriptionPart2_Rabuta:: @ 858A279
	.i18n 5851

gBerryDescriptionPart1_Nomel:: @ 858A293
	.i18n 5852

gBerryDescriptionPart2_Nomel:: @ 858A2B6
	.i18n 5853

gBerryDescriptionPart1_Spelon:: @ 858A2DA
	.i18n 5854

gBerryDescriptionPart2_Spelon:: @ 858A2FF
	.i18n 5855

gBerryDescriptionPart1_Pamtre:: @ 858A324
	.i18n 5856

gBerryDescriptionPart2_Pamtre:: @ 858A346
	.i18n 5857

gBerryDescriptionPart1_Watmel:: @ 858A367
	.i18n 5858

gBerryDescriptionPart2_Watmel:: @ 858A387
	.i18n 5859

gBerryDescriptionPart1_Durin:: @ 858A3AD
	.i18n 5860

gBerryDescriptionPart2_Durin:: @ 858A3CE
	.i18n 5861

gBerryDescriptionPart1_Belue:: @ 858A3F6
	.i18n 5862

gBerryDescriptionPart2_Belue:: @ 858A41C
	.i18n 5863

gBerryDescriptionPart1_Liechi:: @ 858A444
	.i18n 5864

gBerryDescriptionPart2_Liechi:: @ 858A469
	.i18n 5865

gBerryDescriptionPart1_Ganlon:: @ 858A487
	.i18n 5866

gBerryDescriptionPart2_Ganlon:: @ 858A4AC
	.i18n 5867

gBerryDescriptionPart1_Salac:: @ 858A4CB
	.i18n 5868

gBerryDescriptionPart2_Salac:: @ 858A4F0
	.i18n 5869

gBerryDescriptionPart1_Petaya:: @ 858A50E
	.i18n 5870

gBerryDescriptionPart2_Petaya:: @ 858A533
	.i18n 5871

gBerryDescriptionPart1_Apicot:: @ 858A55B
	.i18n 5872

gBerryDescriptionPart2_Apicot:: @ 858A57F
	.i18n 5873

gBerryDescriptionPart1_Lansat:: @ 858A5A6
	.i18n 5874

gBerryDescriptionPart2_Lansat:: @ 858A5C4
	.i18n 5875

gBerryDescriptionPart1_Starf:: @ 858A5E6
	.i18n 5876

gBerryDescriptionPart2_Starf:: @ 858A609
	.i18n 5877

gBerryDescriptionPart1_Enigma:: @ 858A62C
	.i18n 5878

gBerryDescriptionPart2_Enigma:: @ 858A64A
	.i18n 5879

