gText_Birch_Welcome:: @ 82C897B
	.i18n 5880

gText_Birch_Pokemon:: @ 82C89FB
	.i18n 5881

gText_Birch_MainSpeech:: @ 82C8A1F
	.i18n 5882

gText_Birch_AndYouAre:: @ 82C8BD0
	.i18n 5883

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.i18n 5884

gText_Birch_WhatsYourName:: @ 82C8BFF
	.i18n 5885

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.i18n 5886

gText_Birch_YourePlayer:: @ 82C8C2A
	.i18n 5887

gText_Birch_AreYouReady:: @ 82C8C7A
	.i18n 5888
