LilycoveCity_Harbor_Text_2A6848: @ 82A6848
	.i18n 6089

LilycoveCity_Harbor_Text_2A68D2: @ 82A68D2
	.i18n 6090

LilycoveCity_Harbor_Text_2A68FC: @ 82A68FC
	.i18n 6091

SouthernIsland_Exterior_Text_2A69F1: @ 82A69F1
	.i18n 6092

BirthIsland_Harbor_Text_2A6A5D: @ 82A6A5D
FarawayIsland_Entrance_Text_2A6A5D: @ 82A6A5D
NavelRock_Harbor_Text_2A6A5D: @ 82A6A5D
SouthernIsland_Exterior_Text_2A6A5D: @ 82A6A5D
	.i18n 6093

BirthIsland_Harbor_Text_2A6A82: @ 82A6A82
FarawayIsland_Entrance_Text_2A6A82: @ 82A6A82
LilycoveCity_Harbor_Text_2A6A82: @ 82A6A82
NavelRock_Harbor_Text_2A6A82: @ 82A6A82
SouthernIsland_Exterior_Text_2A6A82: @ 82A6A82
	.i18n 6094

SouthernIsland_Interior_Text_2A6AA1: @ 82A6AA1
	.i18n 6095

SouthernIsland_Exterior_Text_2A6AD5: @ 82A6AD5
	.i18n 6096
