LilycoveCity_DepartmentStore_1F_Text_2A6390: @ 82A6390
	.i18n 6097

LilycoveCity_DepartmentStore_1F_Text_2A6496: @ 82A6496
	.i18n 6098

LilycoveCity_DepartmentStore_1F_Text_2A64B1: @ 82A64B1
	.i18n 6099

LilycoveCity_DepartmentStore_1F_Text_2A64C8: @ 82A64C8
	.i18n 6100

LilycoveCity_DepartmentStore_1F_Text_2A650B: @ 82A650B
	.i18n 6101

LilycoveCity_DepartmentStore_1F_Text_2A6592: @ 82A6592
	.i18n 6102

LilycoveCity_DepartmentStore_1F_Text_2A65E6: @ 82A65E6
	.i18n 6103

LilycoveCity_DepartmentStore_1F_Text_2A663C: @ 82A663C
	.i18n 6104

LilycoveCity_DepartmentStore_1F_Text_2A6664: @ 82A6664
	.i18n 6105

LilycoveCity_DepartmentStore_1F_Text_2A66A7: @ 82A66A7
	.i18n 6106

LilycoveCity_DepartmentStore_1F_Text_2A66ED: @ 82A66ED
	.i18n 6107

LilycoveCity_DepartmentStore_1F_Text_2A6731: @ 82A6731
	.i18n 6108

LilycoveCity_DepartmentStore_1F_Text_2A678C: @ 82A678C
	.i18n 6109

LilycoveCity_DepartmentStore_1F_Text_2A67E1: @ 82A67E1
	.i18n 6110

LilycoveCity_DepartmentStore_1F_Text_2A6831: @ 82A6831
	.i18n 6111
