MatchCall_WildBattleText1:: @ 82A971C
	.i18n 6112

MatchCall_WildBattleText2:: @ 82A9798
	.i18n 6113

MatchCall_WildBattleText3:: @ 82A9813
	.i18n 6114

MatchCall_WildBattleText4:: @ 82A98A8
	.i18n 6115

MatchCall_WildBattleText5:: @ 82A9977
	.i18n 6116

MatchCall_WildBattleText6:: @ 82A99FD
	.i18n 6117

MatchCall_WildBattleText7:: @ 82A9A78
	.i18n 6118

MatchCall_WildBattleText8:: @ 82A9AE8
	.i18n 6119

MatchCall_WildBattleText9:: @ 82A9BA7
	.i18n 6120

MatchCall_WildBattleText10:: @ 82A9C36
	.i18n 6121

MatchCall_WildBattleText11:: @ 82A9CC8
	.i18n 6122

MatchCall_WildBattleText12:: @ 82A9D44
	.i18n 6123

MatchCall_WildBattleText13:: @ 82A9DD7
	.i18n 6124

MatchCall_WildBattleText14:: @ 82A9E70
	.i18n 6125

MatchCall_WildBattleText15:: @ 82A9EFD
	.i18n 6126

MatchCall_NegativeBattleText1:: @ 82A9FAB
	.i18n 6127

MatchCall_NegativeBattleText2:: @ 82AA028
	.i18n 6128

MatchCall_NegativeBattleText3:: @ 82AA099
	.i18n 6129

MatchCall_NegativeBattleText4:: @ 82AA100
	.i18n 6130

MatchCall_NegativeBattleText5:: @ 82AA188
	.i18n 6131

MatchCall_NegativeBattleText6:: @ 82AA214
	.i18n 6132

MatchCall_NegativeBattleText7:: @ 82AA2A1
	.i18n 6133

MatchCall_NegativeBattleText8:: @ 82AA31B
	.i18n 6134

MatchCall_NegativeBattleText9:: @ 82AA3A8
	.i18n 6135

MatchCall_NegativeBattleText10:: @ 82AA442
	.i18n 6136

MatchCall_NegativeBattleText11:: @ 82AA4C5
	.i18n 6137

MatchCall_NegativeBattleText12:: @ 82AA520
	.i18n 6138

MatchCall_NegativeBattleText13:: @ 82AA5AD
	.i18n 6139

MatchCall_NegativeBattleText14:: @ 82AA64D
	.i18n 6140

MatchCall_PositiveBattleText1:: @ 82AA6AF
	.i18n 6141

MatchCall_PositiveBattleText2:: @ 82AA730
	.i18n 6142

MatchCall_PositiveBattleText3:: @ 82AA77A
	.i18n 6143

MatchCall_PositiveBattleText4:: @ 82AA81C
	.i18n 6144

MatchCall_PositiveBattleText5:: @ 82AA88C
	.i18n 6145

MatchCall_PositiveBattleText6:: @ 82AA934
	.i18n 6146

MatchCall_PositiveBattleText7:: @ 82AA9D3
	.i18n 6147

MatchCall_PositiveBattleText8:: @ 82AAA40
	.i18n 6148

MatchCall_PositiveBattleText9:: @ 82AAAE4
	.i18n 6149

MatchCall_PositiveBattleText10:: @ 82AAB8C
	.i18n 6150

MatchCall_PositiveBattleText11:: @ 82AAC25
	.i18n 6151

MatchCall_PositiveBattleText12:: @ 82AAC9D
	.i18n 6152

MatchCall_PositiveBattleText13:: @ 82AAD41
	.i18n 6153

MatchCall_PositiveBattleText14:: @ 82AAE00
	.i18n 6154

MatchCall_SameRouteBattleRequestText1:: @ 82AAE7F
	.i18n 6155

MatchCall_SameRouteBattleRequestText2:: @ 82AAEF1
	.i18n 6156

MatchCall_SameRouteBattleRequestText3:: @ 82AAF69
	.i18n 6157

MatchCall_SameRouteBattleRequestText4:: @ 82AB010
	.i18n 6158

MatchCall_SameRouteBattleRequestText5:: @ 82AB076
	.i18n 6159

MatchCall_SameRouteBattleRequestText6:: @ 82AB11A
	.i18n 6160

MatchCall_SameRouteBattleRequestText7:: @ 82AB1B4
	.i18n 6161

MatchCall_SameRouteBattleRequestText8:: @ 82AB23D
	.i18n 6162

MatchCall_SameRouteBattleRequestText9:: @ 82AB2E9
	.i18n 6163

MatchCall_SameRouteBattleRequestText10:: @ 82AB382
	.i18n 6164

MatchCall_SameRouteBattleRequestText11:: @ 82AB410
	.i18n 6165

MatchCall_SameRouteBattleRequestText12:: @ 82AB4B0
	.i18n 6166

MatchCall_SameRouteBattleRequestText13:: @ 82AB538
	.i18n 6167

MatchCall_SameRouteBattleRequestText14:: @ 82AB5E4
	.i18n 6168

MatchCall_DifferentRouteBattleRequestText1:: @ 82AB670
	.i18n 6169

MatchCall_DifferentRouteBattleRequestText2:: @ 82AB6CD
	.i18n 6170

MatchCall_DifferentRouteBattleRequestText3:: @ 82AB73C
	.i18n 6171

MatchCall_DifferentRouteBattleRequestText4:: @ 82AB808
	.i18n 6172

MatchCall_DifferentRouteBattleRequestText5:: @ 82AB8B7
	.i18n 6173

MatchCall_DifferentRouteBattleRequestText6:: @ 82AB95D
	.i18n 6174

MatchCall_DifferentRouteBattleRequestText7:: @ 82ABA03
	.i18n 6175

MatchCall_DifferentRouteBattleRequestText8:: @ 82ABA9F
	.i18n 6176

MatchCall_DifferentRouteBattleRequestText9:: @ 82ABB62
	.i18n 6177

MatchCall_DifferentRouteBattleRequestText10:: @ 82ABC26
	.i18n 6178

MatchCall_DifferentRouteBattleRequestText11:: @ 82ABCE9
	.i18n 6179

MatchCall_DifferentRouteBattleRequestText12:: @ 82ABDA2
	.i18n 6180

MatchCall_DifferentRouteBattleRequestText13:: @ 82ABE5E
	.i18n 6181

MatchCall_DifferentRouteBattleRequestText14:: @ 82ABF36
	.i18n 6182

MatchCall_PersonalizedText1:: @ 82AC009
	.i18n 6183

MatchCall_PersonalizedText2:: @ 82AC0BD
	.i18n 6184

MatchCall_PersonalizedText3:: @ 82AC18C
	.i18n 6185

MatchCall_PersonalizedText4:: @ 82AC228
	.i18n 6186

MatchCall_PersonalizedText5:: @ 82AC30C
	.i18n 6187

MatchCall_PersonalizedText6:: @ 82AC3B6
	.i18n 6188

MatchCall_PersonalizedText7:: @ 82AC446
	.i18n 6189

MatchCall_PersonalizedText8:: @ 82AC5C7
	.i18n 6190

MatchCall_PersonalizedText9:: @ 82AC682
	.i18n 6191

MatchCall_PersonalizedText10:: @ 82AC755
	.i18n 6192

MatchCall_PersonalizedText11:: @ 82AC82C
	.i18n 6193

MatchCall_PersonalizedText12:: @ 82AC914
	.i18n 6194

MatchCall_PersonalizedText13:: @ 82ACA59
	.i18n 6195

MatchCall_PersonalizedText14:: @ 82ACB02
	.i18n 6196

MatchCall_PersonalizedText15:: @ 82ACC3F
	.i18n 6197

MatchCall_PersonalizedText16:: @ 82ACD2F
	.i18n 6198

MatchCall_PersonalizedText17:: @ 82ACE1E
	.i18n 6199

MatchCall_PersonalizedText18:: @ 82ACF32
	.i18n 6200

MatchCall_PersonalizedText19:: @ 82ACFBE
	.i18n 6201

MatchCall_PersonalizedText20:: @ 82AD0AC
	.i18n 6202

MatchCall_PersonalizedText21:: @ 82AD194
	.i18n 6203

MatchCall_PersonalizedText22:: @ 82AD1DF
	.i18n 6204

MatchCall_PersonalizedText23:: @ 82AD2A8
	.i18n 6205

MatchCall_PersonalizedText24:: @ 82AD34F
	.i18n 6206

MatchCall_PersonalizedText25:: @ 82AD44E
	.i18n 6207

MatchCall_PersonalizedText26:: @ 82AD53A
	.i18n 6208

MatchCall_PersonalizedText27:: @ 82AD642
	.i18n 6209

MatchCall_PersonalizedText28:: @ 82AD801
	.i18n 6210

MatchCall_PersonalizedText29:: @ 82AD92E
	.i18n 6211

MatchCall_PersonalizedText30:: @ 82ADA8F
	.i18n 6212

MatchCall_PersonalizedText31:: @ 82ADB9B
	.i18n 6213

MatchCall_PersonalizedText32:: @ 82ADC92
	.i18n 6214

MatchCall_PersonalizedText33:: @ 82ADE08
	.i18n 6215

MatchCall_PersonalizedText34:: @ 82ADF07
	.i18n 6216

MatchCall_PersonalizedText35:: @ 82AE0D9
	.i18n 6217

MatchCall_PersonalizedText36:: @ 82AE1FD
	.i18n 6218

MatchCall_PersonalizedText37:: @ 82AE327
	.i18n 6219

MatchCall_PersonalizedText38:: @ 82AE3DA
	.i18n 6220

MatchCall_PersonalizedText39:: @ 82AE489
	.i18n 6221

MatchCall_PersonalizedText40:: @ 82AE5CD
	.i18n 6222

MatchCall_PersonalizedText41:: @ 82AE698
	.i18n 6223

MatchCall_PersonalizedText42:: @ 82AE704
	.i18n 6224

MatchCall_PersonalizedText43:: @ 82AE78F
	.i18n 6225

MatchCall_PersonalizedText44:: @ 82AE859
	.i18n 6226

MatchCall_PersonalizedText45:: @ 82AE8E6
	.i18n 6227

MatchCall_PersonalizedText46:: @ 82AE998
	.i18n 6228

MatchCall_PersonalizedText47:: @ 82AEA8F
	.i18n 6229

MatchCall_PersonalizedText48:: @ 82AEB77
	.i18n 6230

MatchCall_PersonalizedText49:: @ 82AEBFA
	.i18n 6231

MatchCall_PersonalizedText50:: @ 82AECC1
	.i18n 6232

MatchCall_PersonalizedText51:: @ 82AED52
	.i18n 6233

MatchCall_PersonalizedText52:: @ 82AEE35
	.i18n 6234

MatchCall_PersonalizedText53:: @ 82AEEF4
	.i18n 6235

MatchCall_PersonalizedText54:: @ 82AEFDA
	.i18n 6236

MatchCall_PersonalizedText55:: @ 82AF0E7
	.i18n 6237

MatchCall_PersonalizedText56:: @ 82AF1B8
	.i18n 6238

MatchCall_PersonalizedText57:: @ 82AF2C4
	.i18n 6239

MatchCall_PersonalizedText58:: @ 82AF371
	.i18n 6240

MatchCall_PersonalizedText59:: @ 82AF480
	.i18n 6241

MatchCall_PersonalizedText60:: @ 82AF671
	.i18n 6242

MatchCall_PersonalizedText61:: @ 82AF7D8
	.i18n 6243

MatchCall_PersonalizedText62:: @ 82AF8F7
	.i18n 6244

MatchCall_PersonalizedText63:: @ 82AFA39
	.i18n 6245

MatchCall_PersonalizedText64:: @ 82AFB26
	.i18n 6246

MatchCall_BattleFrontierStreakText1:: @ 82AFC07
	.i18n 6247

MatchCall_BattleFrontierStreakText2:: @ 82AFC78
	.i18n 6248

MatchCall_BattleFrontierStreakText3:: @ 82AFCFF
	.i18n 6249

MatchCall_BattleFrontierStreakText4:: @ 82AFDA7
	.i18n 6250

MatchCall_BattleFrontierStreakText5:: @ 82AFE3D
	.i18n 6251

MatchCall_BattleFrontierStreakText6:: @ 82AFECA
	.i18n 6252

MatchCall_BattleFrontierStreakText7:: @ 82AFF64
	.i18n 6253

MatchCall_BattleFrontierStreakText8:: @ 82AFFF0
	.i18n 6254

MatchCall_BattleFrontierStreakText9:: @ 82B00B5
	.i18n 6255

MatchCall_BattleFrontierStreakText10:: @ 82B0129
	.i18n 6256

MatchCall_BattleFrontierStreakText11:: @ 82B01A5
	.i18n 6257

MatchCall_BattleFrontierStreakText12:: @ 82B0232
	.i18n 6258

MatchCall_BattleFrontierStreakText13:: @ 82B02D9
	.i18n 6259

MatchCall_BattleFrontierStreakText14:: @ 82B0366
	.i18n 6260

MatchCall_BattleFrontierRecordStreakText1:: @ 82B03E6
	.i18n 6261

MatchCall_BattleFrontierRecordStreakText2:: @ 82B0457
	.i18n 6262

MatchCall_BattleFrontierRecordStreakText3:: @ 82B04DE
	.i18n 6263

MatchCall_BattleFrontierRecordStreakText4:: @ 82B0586
	.i18n 6264

MatchCall_BattleFrontierRecordStreakText5:: @ 82B061C
	.i18n 6265

MatchCall_BattleFrontierRecordStreakText6:: @ 82B06A3
	.i18n 6266

MatchCall_BattleFrontierRecordStreakText7:: @ 82B073B
	.i18n 6267

MatchCall_BattleFrontierRecordStreakText8:: @ 82B07C7
	.i18n 6268

MatchCall_BattleFrontierRecordStreakText9:: @ 82B0894
	.i18n 6269

MatchCall_BattleFrontierRecordStreakText10:: @ 82B0908
	.i18n 6270

MatchCall_BattleFrontierRecordStreakText11:: @ 82B0984
	.i18n 6271

MatchCall_BattleFrontierRecordStreakText12:: @ 82B0A11
	.i18n 6272

MatchCall_BattleFrontierRecordStreakText13:: @ 82B0AB8
	.i18n 6273

MatchCall_BattleFrontierRecordStreakText14:: @ 82B0B45
	.i18n 6274

MatchCall_BattleDomeText1:: @ 82B0BC5
	.i18n 6275

MatchCall_BattleDomeText2:: @ 82B0C4A
	.i18n 6276

MatchCall_BattleDomeText3:: @ 82B0CC7
	.i18n 6277

MatchCall_BattleDomeText4:: @ 82B0D4A
	.i18n 6278

MatchCall_BattleDomeText5:: @ 82B0DC8
	.i18n 6279

MatchCall_BattleDomeText6:: @ 82B0E35
	.i18n 6280

MatchCall_BattleDomeText7:: @ 82B0ED1
	.i18n 6281

MatchCall_BattleDomeText8:: @ 82B0F72
	.i18n 6282

MatchCall_BattleDomeText9:: @ 82B102A
	.i18n 6283

MatchCall_BattleDomeText10:: @ 82B10A7
	.i18n 6284

MatchCall_BattleDomeText11:: @ 82B1121
	.i18n 6285

MatchCall_BattleDomeText12:: @ 82B11D3
	.i18n 6286

MatchCall_BattleDomeText13:: @ 82B124D
	.i18n 6287

MatchCall_BattleDomeText14:: @ 82B12D0
	.i18n 6288

MatchCall_BattlePikeText1:: @ 82B1347
	.i18n 6289

MatchCall_BattlePikeText2:: @ 82B13B1
	.i18n 6290

MatchCall_BattlePikeText3:: @ 82B142B
	.i18n 6291

MatchCall_BattlePikeText4:: @ 82B14B4
	.i18n 6292

MatchCall_BattlePikeText5:: @ 82B1525
	.i18n 6293

MatchCall_BattlePikeText6:: @ 82B158E
	.i18n 6294

MatchCall_BattlePikeText7:: @ 82B1622
	.i18n 6295

MatchCall_BattlePikeText8:: @ 82B169D
	.i18n 6296

MatchCall_BattlePikeText9:: @ 82B1775
	.i18n 6297

MatchCall_BattlePikeText10:: @ 82B17F8
	.i18n 6298

MatchCall_BattlePikeText11:: @ 82B1877
	.i18n 6299

MatchCall_BattlePikeText12:: @ 82B1946
	.i18n 6300

MatchCall_BattlePikeText13:: @ 82B19C7
	.i18n 6301

MatchCall_BattlePikeText14:: @ 82B1A4C
	.i18n 6302

MatchCall_BattlePyramidText1:: @ 82B1ACA
	.i18n 6303

MatchCall_BattlePyramidText2:: @ 82B1B50
	.i18n 6304

MatchCall_BattlePyramidText3:: @ 82B1BE4
	.i18n 6305

MatchCall_BattlePyramidText4:: @ 82B1C6A
	.i18n 6306

MatchCall_BattlePyramidText5:: @ 82B1CCF
	.i18n 6307

MatchCall_BattlePyramidText6:: @ 82B1D38
	.i18n 6308

MatchCall_BattlePyramidText7:: @ 82B1DCD
	.i18n 6309

MatchCall_BattlePyramidText8:: @ 82B1E4B
	.i18n 6310

MatchCall_BattlePyramidText9:: @ 82B1F24
	.i18n 6311

MatchCall_BattlePyramidText10:: @ 82B1FA8
	.i18n 6312

MatchCall_BattlePyramidText11:: @ 82B2022
	.i18n 6313

MatchCall_BattlePyramidText12:: @ 82B20F3
	.i18n 6314

MatchCall_BattlePyramidText13:: @ 82B2175
	.i18n 6315

MatchCall_BattlePyramidText14:: @ 82B21FC
	.i18n 6316

gText_Mom_Pokenav_2B227B:: @ 82B227B
	.i18n 6317

gText_Mom_Pokenav_2B2310:: @ 82B2310
	.i18n 6318

gText_Mom_Pokenav_2B23F3:: @ 82B23F3
	.i18n 6319

gText_Roxanne_Pokenav_2B2456:: @ 82B2456
	.i18n 6320

gText_Roxanne_Pokenav_2B250E:: @ 82B250E
	.i18n 6321

gText_Roxanne_Pokenav_2B25C1:: @ 82B25C1
	.i18n 6322

gText_Roxanne_Pokenav_2B2607:: @ 82B2607
	.i18n 6323

gText_Brawly_Pokenav_2B2659:: @ 82B2659
	.i18n 6324

gText_Brawly_Pokenav_2B275D:: @ 82B275D
	.i18n 6325

gText_Brawly_Pokenav_2B286F:: @ 82B286F
	.i18n 6326

gText_Brawly_Pokenav_2B28D1:: @ 82B28D1
	.i18n 6327

gText_Wattson_Pokenav_2B2912:: @ 82B2912
	.i18n 6328

gText_Wattson_Pokenav_2B29CA:: @ 82B29CA
	.i18n 6329

gText_Wattson_Pokenav_2B2AB6:: @ 82B2AB6
	.i18n 6330

gText_Wattson_Pokenav_2B2B01:: @ 82B2B01
	.i18n 6331

gText_Flannery_Pokenav_2B2B4D:: @ 82B2B4D
	.i18n 6332

gText_Flannery_Pokenav_2B2C0E:: @ 82B2C0E
	.i18n 6333

gText_Flannery_Pokenav_2B2CF1:: @ 82B2CF1
	.i18n 6334

gText_Flannery_Pokenav_2B2D54:: @ 82B2D54
	.i18n 6335

gText_Winona_Pokenav_2B2DA4:: @ 82B2DA4
	.i18n 6336

gText_Winona_Pokenav_2B2E2B:: @ 82B2E2B
	.i18n 6337

gText_Winona_Pokenav_2B2EC2:: @ 82B2EC2
	.i18n 6338

gText_Winona_Pokenav_2B2F16:: @ 82B2F16
	.i18n 6339

gText_TateLiza_Pokenav_2B2F97:: @ 82B2F97
	.i18n 6340

gText_TateLiza_Pokenav_2B306E:: @ 82B306E
	.i18n 6341

gText_TateLiza_Pokenav_2B3158:: @ 82B3158
	.i18n 6342

gText_TateLiza_Pokenav_2B31CD:: @ 82B31CD
	.i18n 6343

gText_Juan_Pokenav_2B3249:: @ 82B3249
	.i18n 6344

gText_Juan_Pokenav_2B32EC:: @ 82B32EC
	.i18n 6345

gText_Juan_Pokenav_2B33AA:: @ 82B33AA
	.i18n 6346

gText_Juan_Pokenav_2B341E:: @ 82B341E
	.i18n 6347

gText_Sidney_Pokenav_2B34CC:: @ 82B34CC
	.i18n 6348

gText_Phoebe_Pokenav_2B3561:: @ 82B3561
	.i18n 6349

gText_Glacia_Pokenav_2B35E4:: @ 82B35E4
	.i18n 6350

gText_Drake_Pokenav_2B368B:: @ 82B368B
	.i18n 6351

gText_Wallace_Pokenav_2B3790:: @ 82B3790
	.i18n 6352

MossdeepCity_SpaceCenter_2F_Text_2B38C1: @ 82B38C1
	.i18n 6353

MossdeepCity_SpaceCenter_2F_Text_2B39C6: @ 82B39C6
	.i18n 6354

gText_May_Pokenav_2B3AB3:: @ 2B3AB3
	.i18n 6355

gText_May_Pokenav_2B3B3F:: @ 2B3B3F
	.i18n 6356

gText_May_Pokenav_2B3C13:: @ 2B3C13
	.i18n 6357

gText_May_Pokenav_2B3CF3:: @ 2B3CF3
	.i18n 6358

gText_May_Pokenav_2B3D4B:: @ 2B3D4B
	.i18n 6359

gText_May_Pokenav_2B3DD1:: @ 2B3DD1
	.i18n 6360

gText_May_Pokenav_2B3E69:: @ 2B3E69
	.i18n 6361

gText_May_Pokenav_2B3ECD:: @ 2B3ECD
	.i18n 6362

gText_May_Pokenav_2B3F2B:: @ 2B3F2B
	.i18n 6363

gText_May_Pokenav_2B3FFB:: @ 2B3FFB
	.i18n 6364

gText_May_Pokenav_2B402B:: @ 2B402B
	.i18n 6365

gText_May_Pokenav_2B414B:: @ 2B414B
	.i18n 6366

gText_May_Pokenav_2B4228:: @ 2B4228
	.i18n 6367

gText_May_Pokenav_2B42E0:: @ 2B42E0
	.i18n 6368

gText_May_Pokenav_2B4350:: @ 2B4350
	.i18n 6369

gText_Brendan_Pokenav_2B43EF:: @ 2B43EF
	.i18n 6370

gText_Brendan_Pokenav_2B4486:: @ 2B4486
	.i18n 6371

gText_Brendan_Pokenav_2B4560:: @ 2B4560
	.i18n 6372

gText_Brendan_Pokenav_2B463F:: @ 2B463F
	.i18n 6373

gText_Brendan_Pokenav_2B46B7:: @ 2B46B7
	.i18n 6374

gText_Brendan_Pokenav_2B4761:: @ 2B4761
	.i18n 6375

gText_Brendan_Pokenav_2B47F4:: @ 2B47F4
	.i18n 6376

gText_Brendan_Pokenav_2B4882:: @ 2B4882
	.i18n 6377

gText_Brendan_Pokenav_2B4909:: @ 2B4909
	.i18n 6378

gText_Brendan_Pokenav_2B49C4:: @ 2B49C4
	.i18n 6379

gText_Brendan_Pokenav_2B4A44:: @ 2B4A44
	.i18n 6380

gText_Brendan_Pokenav_2B4B28:: @ 2B4B28
	.i18n 6381

gText_Brendan_Pokenav_2B4C15:: @ 2B4C15
	.i18n 6382

gText_Brendan_Pokenav_2B4CD8:: @ 2B4CD8
	.i18n 6383

gText_Brendan_Pokenav_2B4D46:: @ 2B4D46
	.i18n 6384

gText_Wally_Pokenav_2B4DE2:: @ 2B4DE2
	.i18n 6385

gText_Wally_Pokenav_2B4E57:: @ 2B4E57
	.i18n 6386

gText_Wally_Pokenav_2B4EA5:: @ 2B4EA5
	.i18n 6387

gText_Wally_Pokenav_2B4F41:: @ 2B4F41
	.i18n 6388

gText_Wally_Pokenav_2B4FF3:: @ 2B4FF3
	.i18n 6389

gText_Wally_Pokenav_2B50B1:: @ 2B50B1
	.i18n 6390

gText_Wally_Pokenav_2B5100:: @ 2B5100
	.i18n 6391

gText_Scott_Pokenav_2B5184:: @ 2B5184
	.i18n 6392

gText_Scott_Pokenav_2B5275:: @ 2B5275
	.i18n 6393

gText_Scott_Pokenav_2B5323:: @ 2B5323
	.i18n 6394

gText_Scott_Pokenav_2B53DB:: @ 2B53DB
	.i18n 6395

gText_Scott_Pokenav_2B54A5:: @ 2B54A5
	.i18n 6396

gText_Scott_Pokenav_2B5541:: @ 2B5541
	.i18n 6397

gText_Scott_Pokenav_2B56CA:: @ 2B56CA
	.i18n 6398

gText_Norman_Pokenav_2B5719:: @ 82B5719
	.i18n 6399

gText_Norman_Pokenav_2B5795:: @ 82B5795
	.i18n 6400

gText_Norman_Pokenav_2B584D:: @ 82B584D
	.i18n 6401

gText_Norman_Pokenav_2B58E3:: @ 82B58E3
	.i18n 6402

gText_Norman_Pokenav_2B5979:: @ 82B5979
	.i18n 6403

gText_Norman_Pokenav_2B5A07:: @ 82B5A07
	.i18n 6404

gText_Norman_Pokenav_2B5A69:: @ 82B5A69
	.i18n 6405

gText_Norman_Pokenav_2B5ACF:: @ 82B5ACF
	.i18n 6406

gText_Norman_Pokenav_2B5B5E:: @ 82B5B5E
	.i18n 6407

gText_Steven_Pokenav_2B5B95:: @ 82B5B95
	.i18n 6408

gText_Steven_Pokenav_2B5C53:: @ 82B5C53
	.i18n 6409

gText_Steven_Pokenav_2B5CC9:: @ 82B5CC9
	.i18n 6410

gText_Steven_Pokenav_2B5DB4:: @ 82B5DB4
	.i18n 6411

gText_Steven_Pokenav_2B5E26:: @ 82B5E26
	.i18n 6412

gText_Steven_Pokenav_2B5EA2:: @ 82B5EA2
	.i18n 6413

gText_Steven_Pokenav_2B5ED9:: @ 82B5ED9
	.i18n 6414

Route101_Text_2B5F52: @ 82B5F52
	.i18n 6415

Route101_Text_2B603A: @ 82B603A
	.i18n 6416

gText_MrStone_Pokenav_2B60C0:: @ 82B60C0
	.i18n 6417

gText_MrStone_Pokenav_2B61E6:: @ 82B61E6
	.i18n 6418

gText_MrStone_Pokenav_2B6302:: @ 82B6302
	.i18n 6419

gText_MrStone_Pokenav_2B63A0:: @ 82B63A0
	.i18n 6420

gText_MrStone_Pokenav_2B64A2:: @ 82B64A2
	.i18n 6421

gText_MrStone_Pokenav_2B6526:: @ 82B6526
	.i18n 6422

gText_MrStone_Pokenav_2B65BB:: @ 82B65BB
	.i18n 6423

gText_MrStone_Pokenav_2B6664:: @ 82B6664
	.i18n 6424

gText_MrStone_Pokenav_2B66B1:: @ 82B66B1
	.i18n 6425

gText_MrStone_Pokenav_2B6703:: @ 82B6703
	.i18n 6426

gText_MrStone_Pokenav_2B67ED:: @ 82B67ED
	.i18n 6427
