
gPokeNewsTextSlateport_Upcoming:: @ 0828D0F8
	.i18n 6453

gPokeNewsTextSlateport_Ongoing:: @ 0828D2A1
	.i18n 6454

gPokeNewsTextSlateport_Ending:: @ 0828D3F5
	.i18n 6455

gPokeNewsTextGameCorner_Upcoming:: @ 0828D571
	.i18n 6456

gPokeNewsTextGameCorner_Ongoing:: @ 0828D66F
	.i18n 6457

gPokeNewsTextGameCorner_Ending:: @ 0828D768
	.i18n 6458

gPokeNewsTextLilycove_Upcoming:: @ 0828D875
	.i18n 6459

gPokeNewsTextLilycove_Ongoing:: @ 0828D994
	.i18n 6460

gPokeNewsTextLilycove_Ending:: @ 0828DAC0
	.i18n 6461

gPokeNewsTextBlendMaster_Upcoming:: @ 0828DBEC
	.i18n 6462

gPokeNewsTextBlendMaster_Ongoing:: @ 0828DD9E
	.i18n 6463

gPokeNewsTextBlendMaster_Ending:: @ 0828DF05
	.i18n 6464
