ShoalCave_LowTideEntranceRoom_Text_2A7E0E: @ 82A7E0E
	.i18n 6485

ShoalCave_LowTideEntranceRoom_Text_2A7EB3: @ 82A7EB3
	.i18n 6486

ShoalCave_LowTideEntranceRoom_Text_2A7F37: @ 82A7F37
	.i18n 6487

ShoalCave_LowTideEntranceRoom_Text_2A7FAC: @ 82A7FAC
	.i18n 6488

ShoalCave_LowTideEntranceRoom_Text_2A8012: @ 82A8012
	.i18n 6489

ShoalCave_LowTideEntranceRoom_Text_2A80C6: @ 82A80C6
	.i18n 6490

ShoalCave_LowTideEntranceRoom_Text_2A80F5: @ 82A80F5
	.i18n 6491

ShoalCave_LowTideInnerRoom_Text_2A8169: @ 82A8169
ShoalCave_LowTideLowerRoom_Text_2A8169: @ 82A8169
ShoalCave_LowTideStairsRoom_Text_2A8169: @ 82A8169
	.i18n 6492

ShoalCave_LowTideInnerRoom_Text_2A81A8: @ 82A81A8
	.i18n 6493
