VictoryRoad_B1F_MapScripts:: @ 82364E4
	.byte 0

VictoryRoad_B1F_EventScript_2364E5:: @ 82364E5
	trainerbattle_single TRAINER_SAMUEL, VictoryRoad_B1F_Text_236558, VictoryRoad_B1F_Text_2365AD
	msgbox VictoryRoad_B1F_Text_2365C4, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B1F_EventScript_2364FC:: @ 82364FC
	trainerbattle_single TRAINER_SHANNON, VictoryRoad_B1F_Text_2365FD, VictoryRoad_B1F_Text_23664D
	msgbox VictoryRoad_B1F_Text_236678, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B1F_EventScript_236513:: @ 8236513
	trainerbattle_single TRAINER_MICHELLE, VictoryRoad_B1F_Text_2366C2, VictoryRoad_B1F_Text_23670B
	msgbox VictoryRoad_B1F_Text_23671B, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B1F_EventScript_23652A:: @ 823652A
	trainerbattle_single TRAINER_MITCHELL, VictoryRoad_B1F_Text_236757, VictoryRoad_B1F_Text_236780
	msgbox VictoryRoad_B1F_Text_2367A7, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B1F_EventScript_236541:: @ 8236541
	trainerbattle_single TRAINER_HALLE, VictoryRoad_B1F_Text_2367FD, VictoryRoad_B1F_Text_23683B
	msgbox VictoryRoad_B1F_Text_23684C, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B1F_Text_236558: @ 8236558
	.i18n 4840

VictoryRoad_B1F_Text_2365AD: @ 82365AD
	.i18n 4841

VictoryRoad_B1F_Text_2365C4: @ 82365C4
	.i18n 4842

VictoryRoad_B1F_Text_2365FD: @ 82365FD
	.i18n 4843

VictoryRoad_B1F_Text_23664D: @ 823664D
	.i18n 4844

VictoryRoad_B1F_Text_236678: @ 8236678
	.i18n 4845

VictoryRoad_B1F_Text_2366C2: @ 82366C2
	.i18n 4846

VictoryRoad_B1F_Text_23670B: @ 823670B
	.i18n 4847

VictoryRoad_B1F_Text_23671B: @ 823671B
	.i18n 4848

VictoryRoad_B1F_Text_236757: @ 8236757
	.i18n 4849

VictoryRoad_B1F_Text_236780: @ 8236780
	.i18n 4850

VictoryRoad_B1F_Text_2367A7: @ 82367A7
	.i18n 4851

VictoryRoad_B1F_Text_2367FD: @ 82367FD
	.i18n 4852

VictoryRoad_B1F_Text_23683B: @ 823683B
	.i18n 4853

VictoryRoad_B1F_Text_23684C: @ 823684C
	.i18n 4854

