SeafloorCavern_Room3_MapScripts:: @ 8234937
	.byte 0

SeafloorCavern_Room3_EventScript_234938:: @ 8234938
	trainerbattle_single TRAINER_SHELLY_2, SeafloorCavern_Room3_Text_234966, SeafloorCavern_Room3_Text_234A79
	msgbox SeafloorCavern_Room3_Text_234A8A, MSGBOX_AUTOCLOSE
	end

SeafloorCavern_Room3_EventScript_23494F:: @ 823494F
	trainerbattle_single TRAINER_GRUNT_27, SeafloorCavern_Room3_Text_234B3A, SeafloorCavern_Room3_Text_234BFE
	msgbox SeafloorCavern_Room3_Text_234C04, MSGBOX_AUTOCLOSE
	end

SeafloorCavern_Room3_Text_234966: @ 8234966
	.i18n 4328

SeafloorCavern_Room3_Text_234A79: @ 8234A79
	.i18n 4329

SeafloorCavern_Room3_Text_234A8A: @ 8234A8A
	.i18n 4330

SeafloorCavern_Room3_Text_234B3A: @ 8234B3A
	.i18n 4331

SeafloorCavern_Room3_Text_234BFE: @ 8234BFE
	.i18n 4332

SeafloorCavern_Room3_Text_234C04: @ 8234C04
	.i18n 4333

