MagmaHideout_2F_2R_MapScripts:: @ 8239E07
	.byte 0

MagmaHideout_2F_2R_EventScript_239E08:: @ 8239E08
	trainerbattle_single TRAINER_GRUNT_52, MagmaHideout_2F_2R_Text_239E64, MagmaHideout_2F_2R_Text_239EA5
	msgbox MagmaHideout_2F_2R_Text_239EBB, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_2R_EventScript_239E1F:: @ 8239E1F
	trainerbattle_single TRAINER_GRUNT_43, MagmaHideout_2F_2R_Text_239F31, MagmaHideout_2F_2R_Text_239F71
	msgbox MagmaHideout_2F_2R_Text_239FA1, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_2R_EventScript_239E36:: @ 8239E36
	trainerbattle_single TRAINER_GRUNT_44, MagmaHideout_2F_2R_Text_239FDE, MagmaHideout_2F_2R_Text_23A050
	msgbox MagmaHideout_2F_2R_Text_23A07D, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_2R_EventScript_239E4D:: @ 8239E4D
	trainerbattle_single TRAINER_GRUNT_45, MagmaHideout_2F_2R_Text_23A0E4, MagmaHideout_2F_2R_Text_23A14C
	msgbox MagmaHideout_2F_2R_Text_23A16F, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_2R_Text_239E64: @ 8239E64
	.i18n 2843

MagmaHideout_2F_2R_Text_239EA5: @ 8239EA5
	.i18n 2844

MagmaHideout_2F_2R_Text_239EBB: @ 8239EBB
	.i18n 2845

MagmaHideout_2F_2R_Text_239F31: @ 8239F31
	.i18n 2846

MagmaHideout_2F_2R_Text_239F71: @ 8239F71
	.i18n 2847

MagmaHideout_2F_2R_Text_239FA1: @ 8239FA1
	.i18n 2848

MagmaHideout_2F_2R_Text_239FDE: @ 8239FDE
	.i18n 2849

MagmaHideout_2F_2R_Text_23A050: @ 823A050
	.i18n 2850

MagmaHideout_2F_2R_Text_23A07D: @ 823A07D
	.i18n 2851

MagmaHideout_2F_2R_Text_23A0E4: @ 823A0E4
	.i18n 2852

MagmaHideout_2F_2R_Text_23A14C: @ 823A14C
	.i18n 2853

MagmaHideout_2F_2R_Text_23A16F: @ 823A16F
	.i18n 2854

