SeafloorCavern_Room4_MapScripts:: @ 8234C9B
	.byte 0

SeafloorCavern_Room4_EventScript_234C9C:: @ 8234C9C
	trainerbattle_single TRAINER_GRUNT_7, SeafloorCavern_Room4_Text_234CCA, SeafloorCavern_Room4_Text_234CF3
	msgbox SeafloorCavern_Room4_Text_234CFC, MSGBOX_AUTOCLOSE
	end

SeafloorCavern_Room4_EventScript_234CB3:: @ 8234CB3
	trainerbattle_single TRAINER_GRUNT_9, SeafloorCavern_Room4_Text_234D3A, SeafloorCavern_Room4_Text_234D68
	msgbox SeafloorCavern_Room4_Text_234D79, MSGBOX_AUTOCLOSE
	end

SeafloorCavern_Room4_Text_234CCA: @ 8234CCA
	.i18n 4334

SeafloorCavern_Room4_Text_234CF3: @ 8234CF3
	.i18n 4335

SeafloorCavern_Room4_Text_234CFC: @ 8234CFC
	.i18n 4336

SeafloorCavern_Room4_Text_234D3A: @ 8234D3A
	.i18n 4337

SeafloorCavern_Room4_Text_234D68: @ 8234D68
	.i18n 4338

SeafloorCavern_Room4_Text_234D79: @ 8234D79
	.i18n 4339

