VictoryRoad_B2F_MapScripts:: @ 82368D4
	.byte 0

VictoryRoad_B2F_EventScript_2368D5:: @ 82368D5
	trainerbattle_single TRAINER_VITO, VictoryRoad_B2F_Text_23695F, VictoryRoad_B2F_Text_2369B3
	msgbox VictoryRoad_B2F_Text_2369DE, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_2368EC:: @ 82368EC
	trainerbattle_single TRAINER_OWEN, VictoryRoad_B2F_Text_236A4C, VictoryRoad_B2F_Text_236A92
	msgbox VictoryRoad_B2F_Text_236AAE, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_236903:: @ 8236903
	trainerbattle_single TRAINER_CAROLINE, VictoryRoad_B2F_Text_236AF0, VictoryRoad_B2F_Text_236B14
	msgbox VictoryRoad_B2F_Text_236B2F, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_23691A:: @ 823691A
	trainerbattle_single TRAINER_JULIE, VictoryRoad_B2F_Text_236B88, VictoryRoad_B2F_Text_236C0A
	msgbox VictoryRoad_B2F_Text_236C21, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_236931:: @ 8236931
	trainerbattle_single TRAINER_FELIX, VictoryRoad_B2F_Text_236C67, VictoryRoad_B2F_Text_236CAB
	msgbox VictoryRoad_B2F_Text_236CBA, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_EventScript_236948:: @ 8236948
	trainerbattle_single TRAINER_DIANNE, VictoryRoad_B2F_Text_236D27, VictoryRoad_B2F_Text_236D6E
	msgbox VictoryRoad_B2F_Text_236D8C, MSGBOX_AUTOCLOSE
	end

VictoryRoad_B2F_Text_23695F: @ 823695F
	.i18n 4855

VictoryRoad_B2F_Text_2369B3: @ 82369B3
	.i18n 4856

VictoryRoad_B2F_Text_2369DE: @ 82369DE
	.i18n 4857

VictoryRoad_B2F_Text_236A4C: @ 8236A4C
	.i18n 4858

VictoryRoad_B2F_Text_236A92: @ 8236A92
	.i18n 4859

VictoryRoad_B2F_Text_236AAE: @ 8236AAE
	.i18n 4860

VictoryRoad_B2F_Text_236AF0: @ 8236AF0
	.i18n 4861

VictoryRoad_B2F_Text_236B14: @ 8236B14
	.i18n 4862

VictoryRoad_B2F_Text_236B2F: @ 8236B2F
	.i18n 4863

VictoryRoad_B2F_Text_236B88: @ 8236B88
	.i18n 4864

VictoryRoad_B2F_Text_236C0A: @ 8236C0A
	.i18n 4865

VictoryRoad_B2F_Text_236C21: @ 8236C21
	.i18n 4866

VictoryRoad_B2F_Text_236C67: @ 8236C67
	.i18n 4867

VictoryRoad_B2F_Text_236CAB: @ 8236CAB
	.i18n 4868

VictoryRoad_B2F_Text_236CBA: @ 8236CBA
	.i18n 4869

VictoryRoad_B2F_Text_236D27: @ 8236D27
	.i18n 4870

VictoryRoad_B2F_Text_236D6E: @ 8236D6E
	.i18n 4871

VictoryRoad_B2F_Text_236D8C: @ 8236D8C
	.i18n 4872

