MagmaHideout_3F_2R_MapScripts:: @ 823A3D4
	.byte 0

MagmaHideout_3F_2R_EventScript_23A3D5:: @ 823A3D5
	trainerbattle_single TRAINER_GRUNT_47, MagmaHideout_3F_2R_Text_23A3EC, MagmaHideout_3F_2R_Text_23A4BB
	msgbox MagmaHideout_3F_2R_Text_23A4EF, MSGBOX_AUTOCLOSE
	end

MagmaHideout_3F_2R_Text_23A3EC: @ 823A3EC
	.i18n 2861

MagmaHideout_3F_2R_Text_23A4BB: @ 823A4BB
	.i18n 2862

MagmaHideout_3F_2R_Text_23A4EF: @ 823A4EF
	.i18n 2863

