SlateportCity_SternsShipyard_2F_MapScripts:: @ 820863D
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_20863E:: @ 820863E
	msgbox SlateportCity_SternsShipyard_2F_Text_208650, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_208647:: @ 8208647
	msgbox SlateportCity_SternsShipyard_2F_Text_2086BA, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_208650: @ 8208650
	.i18n 4585

SlateportCity_SternsShipyard_2F_Text_2086BA: @ 82086BA
	.i18n 4586

