SootopolisCity_Gym_B1F_MapScripts:: @ 8225C8A
	.byte 0

SootopolisCity_Gym_B1F_EventScript_225C8B:: @ 8225C8B
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_225D71, SootopolisCity_Gym_B1F_Text_225DB6
	msgbox SootopolisCity_Gym_B1F_Text_225DCF, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_225CA2:: @ 8225CA2
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_225E04, SootopolisCity_Gym_B1F_Text_225E60
	msgbox SootopolisCity_Gym_B1F_Text_225E90, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_225CB9:: @ 8225CB9
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_22646E, SootopolisCity_Gym_B1F_Text_226495
	msgbox SootopolisCity_Gym_B1F_Text_2264BC, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_225CD0:: @ 8225CD0
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_225FBE, SootopolisCity_Gym_B1F_Text_225FEB
	msgbox SootopolisCity_Gym_B1F_Text_225FFE, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_225CE7:: @ 8225CE7
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_226061, SootopolisCity_Gym_B1F_Text_2260B6
	msgbox SootopolisCity_Gym_B1F_Text_2260D1, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_225CFE:: @ 8225CFE
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_226164, SootopolisCity_Gym_B1F_Text_2261A7
	msgbox SootopolisCity_Gym_B1F_Text_2261B5, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_225D15:: @ 8225D15
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_2261F7, SootopolisCity_Gym_B1F_Text_226274
	msgbox SootopolisCity_Gym_B1F_Text_226286, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_225D2C:: @ 8225D2C
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_2262F3, SootopolisCity_Gym_B1F_Text_22633B
	msgbox SootopolisCity_Gym_B1F_Text_226341, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_225D43:: @ 8225D43
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_226388, SootopolisCity_Gym_B1F_Text_2263BD
	msgbox SootopolisCity_Gym_B1F_Text_2263F4, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_225D5A:: @ 8225D5A
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_225ED6, SootopolisCity_Gym_B1F_Text_225F35
	msgbox SootopolisCity_Gym_B1F_Text_225F67, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_225D71: @ 8225D71
	.i18n 4652

SootopolisCity_Gym_B1F_Text_225DB6: @ 8225DB6
	.i18n 4653

SootopolisCity_Gym_B1F_Text_225DCF: @ 8225DCF
	.i18n 4654

SootopolisCity_Gym_B1F_Text_225E04: @ 8225E04
	.i18n 4655

SootopolisCity_Gym_B1F_Text_225E60: @ 8225E60
	.i18n 4656

SootopolisCity_Gym_B1F_Text_225E90: @ 8225E90
	.i18n 4657

SootopolisCity_Gym_B1F_Text_225ED6: @ 8225ED6
	.i18n 4658

SootopolisCity_Gym_B1F_Text_225F35: @ 8225F35
	.i18n 4659

SootopolisCity_Gym_B1F_Text_225F67: @ 8225F67
	.i18n 4660

SootopolisCity_Gym_B1F_Text_225FBE: @ 8225FBE
	.i18n 4661

SootopolisCity_Gym_B1F_Text_225FEB: @ 8225FEB
	.i18n 4662

SootopolisCity_Gym_B1F_Text_225FFE: @ 8225FFE
	.i18n 4663

SootopolisCity_Gym_B1F_Text_226061: @ 8226061
	.i18n 4664

SootopolisCity_Gym_B1F_Text_2260B6: @ 82260B6
	.i18n 4665

SootopolisCity_Gym_B1F_Text_2260D1: @ 82260D1
	.i18n 4666

SootopolisCity_Gym_B1F_Text_226164: @ 8226164
	.i18n 4667

SootopolisCity_Gym_B1F_Text_2261A7: @ 82261A7
	.i18n 4668

SootopolisCity_Gym_B1F_Text_2261B5: @ 82261B5
	.i18n 4669

SootopolisCity_Gym_B1F_Text_2261F7: @ 82261F7
	.i18n 4670

SootopolisCity_Gym_B1F_Text_226274: @ 8226274
	.i18n 4671

SootopolisCity_Gym_B1F_Text_226286: @ 8226286
	.i18n 4672

SootopolisCity_Gym_B1F_Text_2262F3: @ 82262F3
	.i18n 4673

SootopolisCity_Gym_B1F_Text_22633B: @ 822633B
	.i18n 4674

SootopolisCity_Gym_B1F_Text_226341: @ 8226341
	.i18n 4675

SootopolisCity_Gym_B1F_Text_226388: @ 8226388
	.i18n 4676

SootopolisCity_Gym_B1F_Text_2263BD: @ 82263BD
	.i18n 4677

SootopolisCity_Gym_B1F_Text_2263F4: @ 82263F4
	.i18n 4678

SootopolisCity_Gym_B1F_Text_22646E: @ 822646E
	.i18n 4679

SootopolisCity_Gym_B1F_Text_226495: @ 8226495
	.i18n 4680

SootopolisCity_Gym_B1F_Text_2264BC: @ 82264BC
	.i18n 4681

