MagmaHideout_3F_1R_MapScripts:: @ 823A1B2
	.byte 0

MagmaHideout_3F_1R_EventScript_23A1B3:: @ 823A1B3
	trainerbattle_single TRAINER_GRUNT_46, MagmaHideout_3F_1R_Text_23A1E1, MagmaHideout_3F_1R_Text_23A229
	msgbox MagmaHideout_3F_1R_Text_23A246, MSGBOX_AUTOCLOSE
	end

MagmaHideout_3F_1R_EventScript_23A1CA:: @ 823A1CA
	trainerbattle_single TRAINER_GRUNT_53, MagmaHideout_3F_1R_Text_23A293, MagmaHideout_3F_1R_Text_23A353
	msgbox MagmaHideout_3F_1R_Text_23A37C, MSGBOX_AUTOCLOSE
	end

MagmaHideout_3F_1R_Text_23A1E1: @ 823A1E1
	.i18n 2855

MagmaHideout_3F_1R_Text_23A229: @ 823A229
	.i18n 2856

MagmaHideout_3F_1R_Text_23A246: @ 823A246
	.i18n 2857

MagmaHideout_3F_1R_Text_23A293: @ 823A293
	.i18n 2858

MagmaHideout_3F_1R_Text_23A353: @ 823A353
	.i18n 2859

MagmaHideout_3F_1R_Text_23A37C: @ 823A37C
	.i18n 2860

